config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#show'
  resources :users
  resources :hope_shifts, except: [:show]
  resources :fixed_shifts
  
  
  get "calendar/index", to:"calendar#index"
  get "oauth2callback", to:"calendar#callback"
  
  get "hope_shifts/index_user_id", to: 'hope_shifts#index_user_id'
  get "hope_shifts/index_date", to: 'hope_shifts#index_date'
  
  
  
  
  
  get 'news/index', to: 'news#index'
  get 'news/new'
  post 'news/new', to: 'news#create'
  get 'news/:id', to: 'news#show'
  

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixed_shift.rb
class FixedShift < ApplicationRecord
    belongs_to :user
end

app/models/hope_shift.rb
class HopeShift < ApplicationRecord
    belongs_to :user
end

app/models/news.rb
class News < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :hope_shifts
  has_many :fixed_shifts
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/calendar_controller.rb
require "google/apis/calendar_v3"
require "googleauth"
require "googleauth/stores/file_token_store"
require "date"
require "fileutils"

class CalendarController < ApplicationController

  REDIRECT_URI = "https://63a7b1bc88ce48bdb2f6de554f54d0e3.vfs.cloud9.ap-northeast-1.amazonaws.com/oauth2callback".freeze
  APPLICATION_NAME = "ニクバルダカラ 社内ポータルサイト".freeze
  CLIENT_SECRET_PATH = "client_secret.json".freeze
  # The file token.yaml stores the user's access and refresh tokens, and is
  # created automatically when the authorization flow completes for the first
  # time.
  TOKEN_PATH = "credentials.yaml".freeze
  SCOPE = Google::Apis::CalendarV3::AUTH_CALENDAR
  MY_CALENDAR_ID = 'ma51up48bv1hp2u0jqr915hj3s@group.calendar.google.com'

  def index
  end

  def authorize
    client_id = Google::Auth::ClientId.from_file CLIENT_SECRET_PATH
    logger.debug(client_id.id)
    token_store = Google::Auth::Stores::FileTokenStore.new file: TOKEN_PATH
    authorizer = Google::Auth::UserAuthorizer.new client_id, SCOPE, token_store
    user_id = "shny.kch@gmail.com"
    credentials = authorizer.get_credentials user_id
    if credentials.nil?
      code = session[:code]
      url = authorizer.get_authorization_url(base_url: REDIRECT_URI)
      logger.debug(url)
      credentials = authorizer.get_and_store_credentials_from_code(
        user_id: user_id, code: code, base_url: REDIRECT_URI
      )
    end
    credentials
  end

  def callback
    session[:code] = params[:code]
    logger.debug(session[:code])
    calendar = Google::Apis::CalendarV3::CalendarService.new
    calendar.client_options.application_name = APPLICATION_NAME
    calendar.authorization = authorize
    @events = fetchEvents(calendar)
    # render :json => events
    redirect_to controller: :users, action: :show, id: :"1"   
  end

  def fetchEvents(service)
    # Fetch the next 10 events for the user
    calendar_id = MY_CALENDAR_ID
    response = service.list_events(calendar_id,
                                   max_results:   10,
                                   single_events: true,
                                   order_by:      "startTime",
                                   time_min:      DateTime.now.rfc3339)
    puts "Upcoming events:"
    puts "No upcoming events found" if response.items.empty?
    return response.items
    # response.items.each do |event|
    #   start = event.start.date || event.start.date_time
    #   puts "- #{event.summary} (#{start})"
    # end
  end
end

app/controllers/fixed_shifts_controller.rb
class FixedShiftsController < ApplicationController
  def new
    @fixed_shift = FixedShift.new
  end
  
  def create
    FixedShift.create(shift_params)
    redirect_to root_path
  end
  
  private
  def shift_params
    params.require(:fixed_shift).permit(:user_id, :date, :start_time, :end_time)
  end
  
end

app/controllers/hope_shifts_controller.rb
class HopeShiftsController < ApplicationController
  
  def index_user_id
    @hope_shifts = HopeShift.where(user_id: current_user)
  end
  
  def index_date
    # If the date is from the 1st to the 15th of the current month, the date from the 16th to the end of the current month will be displayed.
    # If the date is from the 16th to the end of the month, the date from the 1st to the 15th of the following month will be displayed.
    today = Date.today
    if today.mday <= 15
      start_day = Date.new(today.year, today.mon, 16)
      end_day = today.end_of_month
    else
      start_day = today.next_month.beginning_of_month
      end_day = Date.new(today.year, today.man + 1, 15)
    end
    @hope_shifts = HopeShift.where(date: start_day..end_day).order(:date)
  end
    
  def new
    @hope_shift = HopeShift.new
  end
  
  def create
    HopeShift.create(shift_params)
    redirect_to root_path
  end

  def edit
    @hope_shift = HopeShift.find(params[:id])
  end
  
  def update
    @hope_shift = HopeShift.find(params[:id])
    @hope_shift.update(shift_params)
    redirect_to hope_shifts_path
  end
  
  def destroy
    
  end
  
  private
  def shift_params
    params.require(:hope_shift).permit(:date, :start_time, :end_time, :user_id)
  end
  
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def show
    @user = User.find(1)
    # @shifts = @user.shifts
    @news = News.all
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/fixed_shifts_helper.rb
module FixedShiftsHelper
end

app/helpers/hope_shifts_helper.rb
module HopeShiftsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendar/callback.html.erb
<h1>Calendar#callback</h1>
<p>Find me in app/views/calendar/callback.html.erb</p>

app/views/calendar/index.html.erb
<h1>Calendar#index</h1>
<p>Find me in app/views/calendar/index.html.erb</p>

app/views/fixed_shifts/new.html.erb
<%= form_for(@fixed_shift) do |f| %>
  <%= f.label :user_id, "ユーザー：" %>
  <%= f.number_field :user_id %>
  <%= f.label :date, "日程：" %>
  <%= f.date_field :date %>
  <%= f.label :start_time, "開始時間：" %>
  <%= f.time_select :start_time %>
  <%= f.label :end_time, "終了時刻：" %>
  <%= f.time_select :end_time %>
  <%= f.submit "送信" %>
<% end %>

app/views/hope_shifts/_form.html.erb
<%= form_for(@hope_shift) do |f| %>
  <%= f.label :date, "日程：" %>
  <%= f.date_field :date %>
  <%= f.label :start_time, "開始時間：" %>
  <%= f.time_select :start_time %>
  <%= f.label :end_time, "終了時刻：" %>
  <%= f.time_select :end_time %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "送信" %>
<% end %>

app/views/hope_shifts/edit.html.erb
<%= render partial: 'form.html.erb' %>

app/views/hope_shifts/index_date.html.erb
<% @hope_shifts.each do |shift| %>
  <p>
    <%= shift.user.name %>
    <%= shift.date %>：
    <%= shift.start_time.strftime('%H:%M') %>〜
    <%= shift.end_time.strftime('%H:%M') %>
  </p>
<% end %>

app/views/hope_shifts/index_user_id.html.erb
<% @hope_shifts.each do |shift| %>
  <p>
    <%= shift.date %>：
    <%= shift.start_time.strftime('%H:%M') %>〜
    <%= shift.end_time.strftime('%H:%M') %>
    <%= link_to "編集", edit_hope_shift_path(shift.id) %>
  </p>
<% end %>

app/views/hope_shifts/new.html.erb
<h1>新規作成</h1>
  <%= form_for(@hope_shift) do |f| %>
  <th>日程</th>
  <%= f.date_field :date %>
  <th>開始時間</th>
  <%= f.time_select :start_time %>
  <th>終了時刻</th>
  <%= f.time_select :end_time %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "送信" %>
  
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NikubaruShiftManagement</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--以下ヘッダー-->
    <nav class="navbar navbar-dark mt-3 ml-2 mr-2" >
      <%= link_to image_tag("header-logo.png"), root_path %>
    </nav>
    <!--ここまで-->
    <!--<p class="notice"><%= notice %></p>-->
    <!--<p class="alert"><%= alert %></p>-->
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid p-3">
  <div class="row no-gutters">
    <div class="col-md">
      <div class="card mr-2">
        <h1 class="ml-2 mt-1>">News</h1>
        <!--<a class="btn btn-dark" href="/news/new" role="button">投稿</a>-->
        <ul class="list-group list-group-flush p-1">
          <% @news.each do |news| %>
            <p>
              <h5><%= news.title %></h5>
              <%= news.text %>
            </p>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md">
      <div class="card ml-2">
        <h1 class="ml-2 mt-1">Shift</h1>
          <% if current_user.id === 1 %>
            <%= button_to "確定シフトを作成", new_fixed_shift_path, {method: :get} if current_user.id === 1 %>
            <%= button_to "全スタッフの希望シフトを確認", hope_shifts_index_date_path, {method: :get} if current_user.id === 1 %>
          <% else %>
            <%= button_to "希望シフトを投稿", {controller: 'hope_shifts', action: 'new'}, {method: :get} %>
            <%= button_to "希望シフトを確認", hope_shifts_index_user_id_path, {method: :get} %>
          <% end %>
        
        <div class="ml-2 mr-2 mb-2" id="calendar"></div>
        <div id="calendar"></div>
        
      </div>
    </div>
  </div>
</div>

<script>
  $(function () {
    // 画面遷移を検知
    $(document).on('turbolinks:load', function () {
        // lengthを呼び出すことで、#calendarが存在していた場合はtrueの処理がされ、無い場合はnillを返す
        if ($('#calendar').length) {
            function eventCalendar() {
                return $('#calendar').fullCalendar({
                });
            };
            function clearCalendar() {
                $('#calendar').html('');
            };

            $(document).on('turbolinks:load', function () {
                eventCalendar();
            });
            $(document).on('turbolinks:before-cache', clearCalendar);

            $('#calendar').fullCalendar({
                events: 'callback.json'
            });
        }
    });
});


</script>